version: '2'
services:
  micropython:
    image: micropython_docker
    build: .
    ports:
      - 8000-8080:8080
    command: sh -c "./micropython boot.py $$(cat /etc/hostname)"
    depends_on:
      - mosquitto
      - bridge
      - grafana
      - influxdb
    links:
      - "mosquitto:mosquitto"
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
  influxdb:
    container_name: influxdb
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./tig/data/influxdb:/var/lib/influxdb
      - ./tig/conf/influxdb:/etc/influxdb/
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana:Z
      # - /tig/data/grafana:/var/lib/grafana
      # - /tig/log/grafana:/var/log/grafana
      # - ./grafana-data/grafana.ini:/etc/grafana/grafana.ini
    links:
      - influxdb
    restart: always
  bridge:
    container_name: bridge
    build: ./bridge
    volumes:
      - ./bridge/mqtt2influxdb.yml:/etc/bigclown/mqtt2influxdb.yml
    command: sh -c "mqtt2influxdb -c /etc/bigclown/mqtt2influxdb.yml"
    depends_on:
      - mosquitto
      - influxdb
    links:
      - mosquitto