version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ./conf/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./conf/mosquitto/data/:/var/lib/mosquitto/
    depends_on:
      - influxdb
    networks:
      - net

  influxdb:
    container_name: influxdb
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./tig/data/influxdb:/var/lib/influxdb
      - ./tig/conf/influxdb:/etc/influxdb/
    restart: always
    networks:
      - net

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - net

  logstash_exporter:
    container_name: logstash_exporter
    image: bonniernews/logstash_exporter
    ports:
      - 9198:9198
    command: --web.listen-address=:9198 --logstash.endpoint="http://logstash:9600"
    depends_on: 
      - logstash
      - prometheus
    networks:
      - net

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment: 
      - discovery.type=single-node
    volumes:
      - ./es-data:/usr/share/elasticsearch/data/
    ports: 
      - "9200:9200"
    networks:
      - net

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.7.0
    ports:
      - "5959:5959"
      - "9600:9600"
    volumes:
      - ./conf/logstash:/config-dir
    command: logstash -f /config-dir/logstash.conf
    links:
      - elasticsearch
      - prometheus
    depends_on:
      - elasticsearch
      - prometheus
    networks:
      - net

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.7.0
    volumes:
      - ./conf/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - net

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana:Z
      # - /tig/data/grafana:/var/lib/grafana
      # - /tig/log/grafana:/var/log/grafana
      # - ./grafana-data/grafana.ini:/etc/grafana/grafana.ini
    links:
      - influxdb
    restart: always
    networks:
      - net

  bridge:
    container_name: bridge
    build: ./bridge
    volumes:
      - ./bridge/mqtt2influxdb.yml:/etc/bigclown/mqtt2influxdb.yml
    command: sh -c "mqtt2influxdb -c /etc/bigclown/mqtt2influxdb.yml"
    depends_on:
      - mosquitto
      - influxdb
    links:
      - mosquitto
    networks:
    - net

  micropython_1:
    container_name: micropython_1
    build: .
    ports:
      - 8000:8080
    environment: 
      CAPABILITIES: "micropython temperature humidity"
    command: sh -c "./micropython boot.py $$(cat /etc/hostname) $$(hostname -i) $${CAPABILITIES}"
    depends_on:
      - mosquitto
      - bridge
      - grafana
      - influxdb
      - logstash_exporter
    links:
      - "mosquitto:mosquitto"
    networks:
      net:
        ipv4_address: 192.165.0.70

  micropython_2:
    container_name: micropython_2
    build: .
    ports:
      - 8001:8080
    environment: 
      CAPABILITIES: "micropython temperature humidity fail"
    command: sh -c "./micropython boot.py $$(cat /etc/hostname) $$(hostname -i) $${CAPABILITIES}"
    depends_on:
      - mosquitto
      - bridge
      - grafana
      - influxdb
      - logstash_exporter
    links:
      - "mosquitto:mosquitto"
    networks:
      net:
        ipv4_address: 192.165.0.71

  micropython_3:
    container_name: micropython_3
    build: .
    ports:
      - 8002:8080
    environment: 
      CAPABILITIES: "micropython temperature humidity"
    command: sh -c "./micropython boot.py $$(cat /etc/hostname) $$(hostname -i) $${CAPABILITIES}"
    depends_on:
      - mosquitto
      - bridge
      - grafana
      - influxdb
      - logstash_exporter
    links:
      - "mosquitto:mosquitto"
    networks:
      net:
        ipv4_address: 192.165.0.72

  micropython_4:
    container_name: micropython_4
    build: .
    ports:
      - 8003:8080
    environment: 
      CAPABILITIES: "micropython fail"
    command: sh -c "./micropython boot.py $$(cat /etc/hostname) $$(hostname -i) $${CAPABILITIES}"
    depends_on:
      - mosquitto
      - bridge
      - grafana
      - influxdb
      - logstash_exporter 
    links:
      - "mosquitto:mosquitto"
    networks:
      net:
        ipv4_address: 192.165.0.73

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 192.165.0.0/24